force-app/main/default/objects/Contract_and_Form_Query__c/Contract_and_Form_Query__c.object-meta.xml
<CustomObject>
    <description>Retrieves data to be merged into a contract and form</description>
    <label>Contract and Form Query</label>
    <nameField>
        <label>Contract and Form Query Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract and Form Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_and_Form_Query__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>A unique name for this query. Used to reference this query in contract and form templates.</description>
    <externalId>true</externalId>
    <inlineHelpText>A unique name for this query. Used to reference this query in contract and form templates.</inlineHelpText>
    <label>Key</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract_and_Form_Query__c/fields/SOQL_Query__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Query__c</fullName>
    <label>SOQL Query</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract_and_Form_Template_Query__c/Contract_and_Form_Template_Query__c.object-meta.xml
<CustomObject>
    <description>Junction object links a Contract and Form Query to a Contract and Form Template</description>
    <label>Contract and Form Template Query</label>
    <nameField>
        <displayFormat>CTQ-{00000}</displayFormat>
        <label>Contract and Form Template Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract and Form Template Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_and_Form_Template_Query__c/fields/Contract_and_Form_Query__c.field-meta.xml
<CustomField>
    <fullName>Contract_and_Form_Query__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract and Form Query</label>
    <referenceTo>Contract_and_Form_Query__c</referenceTo>
    <relationshipLabel>Contract and Form Template Queries</relationshipLabel>
    <relationshipName>Contract_and_Form_Template_Queries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContractTemplateService.cls
/***********************************************************************
 * @license
 * MIT License
 * Copyright (c) 2025 Asphalt Green, Inc.
 * See the LICENSE file in the project root for full license text.
 * 
 * @description
 * Caches templates and associated queries for re-use
 * 
 * @date 2025
 * @author
 * Asphalt Green Data and Information Systems
 ***********************************************************************/
public with sharing class ContractTemplateService {

    private static Map<Id, TREX1__Contract_or_Form_Template__c> templateMap = new Map<Id, TREX1__Contract_or_Form_Template__c>();
    private static Map<String, String> contractQueriesByKeys = new Map<String, String>();

    public static Map<Id, TREX1__Contract_or_Form_Template__c> getTemplates() {
        return templateMap;
    }

    public static Map<String, String> getContractQueriesByKeys() {
        return contractQueriesByKeys;
    }

    public static void addTemplates(Set<Id> templateIds) {
        Set<Id> templateIdsToAdd = new Set<Id>();
        for (Id templateId : templateIds) {
            if (!templateMap.containsKey(templateId)) {
                templateIdsToAdd.add(templateId);
            }
        }
        loadTemplates(templateIdsToAdd);
    }

    private static void loadTemplates(Set<Id> templateIdsToAdd) {
        for (List<TREX1__Contract_or_Form_Template__c> templates : [
            SELECT Id, TREX1__Waiver_Text__c,
                   (SELECT Contract_and_Form_Query__r.Key__c, Contract_and_Form_Query__r.SOQL_Query__c
                      FROM Contract_and_Form_Template_Queries__r)
              FROM TREX1__Contract_or_Form_Template__c
             WHERE Id IN :templateIdsToAdd
              WITH USER_MODE
        ]) {
            for (TREX1__Contract_or_Form_Template__c template : templates) {
                templateMap.put(template.Id, template);
                
                for (Contract_and_Form_Template_Query__c templateQuery : template.Contract_and_Form_Template_Queries__r) {
                    contractQueriesByKeys.put(
                        templateQuery.Contract_and_Form_Query__r.Key__c, 
                        templateQuery.Contract_and_Form_Query__r.SOQL_Query__c
                    );
                }
            }
        }
    }

}